### ISSUE TITLE
Support for new versions of Resharper

### ISSUE THREAD

**Issue by ludekcakl** [nuke-build/resharper#10]
Hello guys,
do you have any plans to add support for new versions of Resharper? I am using Resharper 2017.3 and this extension is not available via Resharper Extension Manager.

**Comment by matkoch** [comment]
The current plugin is built for 2018.1 ... Any reason why you can't install the latest ReSharper version?

**Comment by ludekcakl** [comment]
sorry, my mistake.. I have upgraded Resharper to latest version and now I can install and use this extension. Thanks
